name: CCPlanView
options:
  bundleIdPrefix: sh.saqoo
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.10.0"
    CURRENT_PROJECT_VERSION: "18"
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.0"

targets:
  CCPlanView:
    type: application
    platform: macOS
    sources:
      - path: Sources/CCPlanView
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: notifier
        embed: true
        codeSign: true
        copy:
          destination: executables
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: sh.saqoo.ccplanview
      PRODUCT_NAME: "CCPlanView"
      INFOPLIST_FILE: Sources/CCPlanView/Info.plist
      GENERATE_INFOPLIST_FILE: false
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: G5G54TCH8W
      ENABLE_HARDENED_RUNTIME: YES
      CODE_SIGN_ENTITLEMENTS: Sources/CCPlanView/CCPlanView.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
    info:
      path: Sources/CCPlanView/Info.plist
      properties:
        CFBundleName: "CCPlanView"
        CFBundleDisplayName: "CCPlanView"
        CFBundleIdentifier: sh.saqoo.ccplanview
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleIconName: AppIcon
        CFBundleExecutable: "CCPlanView"
        LSMinimumSystemVersion: "15.0"
        NSHighResolutionCapable: true
        LSApplicationCategoryType: public.app-category.developer-tools
        NSHumanReadableCopyright: "© 2026 Saqoosha. MIT License."
        CFBundleURLTypes:
          - CFBundleURLName: CCPlanView URL Scheme
            CFBundleURLSchemes:
              - ccplanview
        CFBundleDocumentTypes:
          - CFBundleTypeName: Markdown Document
            CFBundleTypeRole: Viewer
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - net.daringfireball.markdown
              - public.plain-text
            CFBundleTypeExtensions:
              - md
              - markdown
              - mdown
              - mkd
        UTImportedTypeDeclarations:
          - UTTypeIdentifier: net.daringfireball.markdown
            UTTypeDescription: Markdown Document
            UTTypeConformsTo:
              - public.plain-text
            UTTypeTagSpecification:
              public.filename-extension:
                - md
                - markdown
                - mdown
                - mkd

  notifier:
    type: tool
    platform: macOS
    sources:
      - path: Sources/notifier
        excludes:
          - "**/.DS_Store"
    settings:
      PRODUCT_NAME: "notifier"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: G5G54TCH8W
      ENABLE_HARDENED_RUNTIME: YES
