name: MarkdownViewer
options:
  bundleIdPrefix: sh.saqoo
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  MarkdownViewer:
    type: application
    platform: macOS
    sources:
      - path: Sources/MarkdownViewer
        excludes:
          - "**/.DS_Store"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: sh.saqoo.markdown-viewer
      PRODUCT_NAME: "Markdown Viewer"
      INFOPLIST_FILE: Sources/MarkdownViewer/Info.plist
      GENERATE_INFOPLIST_FILE: false
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: G5G54TCH8W
      ENABLE_HARDENED_RUNTIME: YES
      CODE_SIGN_ENTITLEMENTS: Sources/MarkdownViewer/MarkdownViewer.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
    info:
      path: Sources/MarkdownViewer/Info.plist
      properties:
        CFBundleName: "Markdown Viewer"
        CFBundleDisplayName: "Markdown Viewer"
        CFBundleIdentifier: sh.saqoo.markdown-viewer
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: "Markdown Viewer"
        LSMinimumSystemVersion: "14.0"
        NSHighResolutionCapable: true
        LSApplicationCategoryType: public.app-category.developer-tools
        NSHumanReadableCopyright: "© 2026 Saqoosha. MIT License."
        CFBundleDocumentTypes:
          - CFBundleTypeName: Markdown Document
            CFBundleTypeRole: Viewer
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - net.daringfireball.markdown
              - public.plain-text
            CFBundleTypeExtensions:
              - md
              - markdown
              - mdown
              - mkd
        UTImportedTypeDeclarations:
          - UTTypeIdentifier: net.daringfireball.markdown
            UTTypeDescription: Markdown Document
            UTTypeConformsTo:
              - public.plain-text
            UTTypeTagSpecification:
              public.filename-extension:
                - md
                - markdown
                - mdown
                - mkd
